name: deploy

env:
  tf_working_directory: ./deploy/terraform
  TF_LOG: DEBUG

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: tf init
        working-directory: ${{env.tf_working_directory}}
        run: |
          terraform init -upgrade -input=false 

      - name: tf validate
        working-directory: ${{env.tf_working_directory}}
        run: |
          terraform validate

      - name: tf plan
        working-directory: ${{env.tf_working_directory}}
        timeout-minutes: 2
        env:
          TF_VAR_CLIENT_SECRET: ${{secrets.TF_VAR_CLIENT_SECRET}}
        run: |
          terraform plan -input=false 
