name: deploy

env:
  tf_working_directory: ./deploy/terraform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: tf plan
        working-directory: ${{env.tf_working_directory}}
        run: |
          terraform init -upgrade /
            -backend-config=subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }} / /
            -backend-config=tenant_id=${{ secrets.ARM_TENANT_ID }} /
            -backend-config=client_id=${{ secrets.ARM_CLIENT_ID }} /
            -backend-config=client_secret=${{ secrets.ARM_CLIENT_SECRET }}

          terraform validate
          terraform plan
