name: stop

env:
  cluster_name: mumby-aks
  resource_group: rg-mumby-aks
  

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  stop_aks:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        name: Az Login
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Stop Cluster
        run: |
          az aks stop --name ${{ env.cluster_name }} --resource-group ${{ env.resource_group }}